// =============================================================================
// Firestore Service (Mock – AsyncStorage backed)
// College Visit Platform
// =============================================================================
// In the prototype every read falls through to mock data and every write is
// persisted via AsyncStorage. When migrating to MVP, swap each function body
// to use the real Firestore SDK imported from ./firebase.ts.
// =============================================================================

import AsyncStorage from '@react-native-async-storage/async-storage';
import type {
  School,
  AcademicData,
  AnalyticsEvent,
  JerseySelection,
} from '@/types';

// Storage key constants
const FAVORITES_KEY = 'college_visit_favorites';
const ANALYTICS_KEY = 'college_visit_analytics';
const JERSEY_KEY = 'college_visit_jerseys';

// -----------------------------------------------------------------------------
// Schools
// -----------------------------------------------------------------------------

/**
 * Get all schools.
 *
 * Reads from the mock data module. In MVP this will query the `schools`
 * Firestore collection.
 */
export async function getSchools(): Promise<School[]> {
  // Attempt to read any locally-overridden school data first
  const raw = await AsyncStorage.getItem('college_visit_schools');
  if (raw) {
    try {
      return JSON.parse(raw) as School[];
    } catch {
      // Fall through to empty array; mock data should be loaded by the data layer
    }
  }
  return [];
}

/**
 * Get a single school by its ID.
 */
export async function getSchool(id: string): Promise<School | null> {
  const schools = await getSchools();
  return schools.find((s) => s.id === id) ?? null;
}

// -----------------------------------------------------------------------------
// Favorites
// -----------------------------------------------------------------------------

/** Internal helper to load the favorites map from AsyncStorage. */
async function loadFavoritesMap(): Promise<Record<string, string[]>> {
  const raw = await AsyncStorage.getItem(FAVORITES_KEY);
  if (!raw) return {};
  try {
    return JSON.parse(raw) as Record<string, string[]>;
  } catch {
    return {};
  }
}

/** Internal helper to persist the favorites map. */
async function saveFavoritesMap(
  map: Record<string, string[]>,
): Promise<void> {
  await AsyncStorage.setItem(FAVORITES_KEY, JSON.stringify(map));
}

/**
 * Get the list of school IDs a user has favorited.
 */
export async function getUserFavorites(userId: string): Promise<string[]> {
  const map = await loadFavoritesMap();
  return map[userId] ?? [];
}

/**
 * Toggle a school's favorite status for a user.
 *
 * Returns the updated list of favorite school IDs.
 */
export async function toggleFavorite(
  userId: string,
  schoolId: string,
): Promise<string[]> {
  const map = await loadFavoritesMap();
  const current = map[userId] ?? [];

  const index = current.indexOf(schoolId);
  if (index === -1) {
    current.push(schoolId);
  } else {
    current.splice(index, 1);
  }

  map[userId] = current;
  await saveFavoritesMap(map);
  return current;
}

// -----------------------------------------------------------------------------
// Analytics
// -----------------------------------------------------------------------------

/**
 * Get all analytics events for a specific school.
 */
export async function getAnalyticsForSchool(
  schoolId: string,
): Promise<AnalyticsEvent[]> {
  const raw = await AsyncStorage.getItem(ANALYTICS_KEY);
  if (!raw) return [];

  try {
    const events = JSON.parse(raw) as AnalyticsEvent[];
    return events.filter((e) => e.schoolId === schoolId);
  } catch {
    return [];
  }
}

/**
 * Get all analytics events generated by a specific recruit/user.
 */
export async function getAnalyticsForRecruit(
  userId: string,
): Promise<AnalyticsEvent[]> {
  const raw = await AsyncStorage.getItem(ANALYTICS_KEY);
  if (!raw) return [];

  try {
    const events = JSON.parse(raw) as AnalyticsEvent[];
    return events.filter((e) => e.userId === userId);
  } catch {
    return [];
  }
}

// -----------------------------------------------------------------------------
// Jersey Selections
// -----------------------------------------------------------------------------

/**
 * Save a jersey/uniform selection.
 *
 * Appends the selection to the stored array for the corresponding school.
 */
export async function saveJerseySelection(
  selection: JerseySelection,
): Promise<void> {
  const raw = await AsyncStorage.getItem(JERSEY_KEY);
  let selections: JerseySelection[] = [];

  if (raw) {
    try {
      selections = JSON.parse(raw) as JerseySelection[];
    } catch {
      selections = [];
    }
  }

  // Replace any existing selection by the same user for the same school
  const existingIndex = selections.findIndex(
    (s) => s.userId === selection.userId && s.schoolId === selection.schoolId,
  );

  if (existingIndex !== -1) {
    selections[existingIndex] = selection;
  } else {
    selections.push(selection);
  }

  await AsyncStorage.setItem(JERSEY_KEY, JSON.stringify(selections));
}

/**
 * Get all jersey selections for a specific school.
 */
export async function getJerseySelections(
  schoolId: string,
): Promise<JerseySelection[]> {
  const raw = await AsyncStorage.getItem(JERSEY_KEY);
  if (!raw) return [];

  try {
    const selections = JSON.parse(raw) as JerseySelection[];
    return selections.filter((s) => s.schoolId === schoolId);
  } catch {
    return [];
  }
}
